/* eslint-disable quote-props */
export default {
  'Anchor': 'mdi:anchor',
  'Apple': 'fluent:food-apple-20-filled',
  'Axe': 'mdi:axe-battle',
  'Backpack': 'jam:backpack-f',
  'Bed': 'mdi:seat-individual-suite',
  'Beer': 'fa:beer',
  'Bin': 'mdi:delete',
  'Biohazard': 'fa-solid:biohazard',
  'Bird': 'mdi:bird',
  'Bone': 'si-glyph:bone',
  'Book': 'mdi:import-contacts',
  'Bow and Arrow': 'mdi:bow-arrow',
  'Brain': 'fa-solid:brain',
  'Bridge': 'icon-park-outline:bridge-one',
  'Butterfly': 'mdi:butterfly',
  'Campfire': 'mdi:campfire',
  'Castle': 'ic:baseline-castle',
  'Chain': 'fa:chain',
  'Chest': 'mdi:treasure-chest',
  'Church': 'fa-solid:church',
  'Climb': 'map:climbing',
  'Cloud': 'mdi:image-filter-drama',
  'Coin Hand': 'mdi:hand-coin',
  'Coin Purse': 'clarity:coin-bag-solid',
  'Coins': 'system-uicons:coins',
  'Compass': 'mdi:explore',
  'Cross': 'mdi:close',
  'D10': 'mdi:dice-d10',
  'D12': 'mdi:dice-d12',
  'D20 Outline': 'fa-solid:dice-d20',
  'D20': 'mdi:dice-d20',
  'D4': 'mdi:dice-d4',
  'D6': 'mdi:dice-d6',
  'D8': 'mdi:dice-d8',
  'Die': 'mdi:casino',
  'Door Open': 'fa-solid:door-open',
  'Double Dice': 'fa-solid:dice',
  'Double Sword': 'ri:sword-line',
  'Dragon': 'fa-solid:dragon',
  'Eat': 'mdi:restaurant',
  'Eclipse': 'mdi:moon-waning-crescent',
  'Educate': 'mdi:school',
  'Egg': 'mdi:egg-outline',
  'Exclamation': 'mdi:error',
  'Eye': 'mdi:visibility',
  'Feet': 'si-glyph:foot-sign',
  'Fire': 'ant-design:fire-filled',
  'Fish': 'fa-solid:fish',
  'Fist': 'fa-solid:fist-raised',
  'Flower': 'ph:flower-lotus-fill',
  'Frost': 'mdi:ac-unit',
  'Gem': 'fa-solid:gem',
  'Glasses': 'fa-solid:glasses',
  'Grass': 'ic:baseline-grass',
  'Guitar': 'fa-solid:guitar',
  'Hammer': 'mdi:hammer',
  'Health': 'healthicons:health',
  'Heart': 'mdi:favorite',
  'Heavy': 'mdi:fitness-center',
  'History': 'mdi:history',
  'Home': 'fluent:home-12-filled',
  'Horse': 'mdi:horse-variant',
  'Hourglass': 'fa6-solid:hourglass',
  'Info': 'heroicons-outline:information-circle',
  'Inject': 'whh:antivirus',
  'Key': 'mdi:vpn-key',
  'Keyhole': 'icon-park-outline:keyhole',
  'Knife': 'mdi:knife',
  'Layout': 'ic:baseline-backup-table',
  'Leaf': 'fa-solid:leaf',
  'Light': 'mdi:brightness-high',
  'Lightning': 'mdi:flash-on',
  'Loud': 'fluent:megaphone-loud-20-filled',
  'Map': 'mdi:map',
  'Moon': 'ic:baseline-nights-stay',
  'Mountain': 'mdi:terrain',
  'Muscle': 'icon-park-outline:muscle',
  'Necklace': 'mdi:necklace',
  'Note': 'mdi:note',
  'People Pair': 'fa-solid:people-arrows',
  'Person': 'mdi:person',
  'Pickaxe': 'mdi:pickaxe',
  'Play': 'mdi:play-circle',
  'Potion': 'mdi:flask',
  'Pray': 'la:praying-hands',
  'Question': 'fa-solid:question',
  'Rabbit': 'mdi:rabbit',
  'Rain': 'fa-solid:cloud-rain',
  'Redo': 'mdi:replay',
  'Religion': 'fa-solid:bible',
  'Ring': 'icon-park-outline:diamond-ring',
  'Run': 'mdi:run',
  'Sailing': 'mdi:sailing',
  'Scales': 'fa-solid:balance-scale',
  'Setting': 'mdi:settings',
  'Shield Faith': 'mdi:shield-cross-outline',
  'Shield Sword': 'mdi:shield-sword-outline',
  'Shield Tick': 'mdi:shield-check-outline',
  'Sick': 'mdi:emoticon-sick-outline',
  'Silent': 'mdi:volume-off',
  'Skull': 'fa-solid:skull-crossbones',
  'Speech': 'cil:speech',
  'Staff': 'mdi:magic-staff',
  'Star Bubble': 'emojione-monotone:right-anger-bubble',
  'Star': 'mdi:grade',
  'Switch': 'mdi:autorenew',
  'Sword': 'vaadin:sword',
  'Tent': 'fluent:tent-12-filled',
  'Text': 'mdi:text',
  'Tick': 'mdi:check',
  'Time': 'mdi:access-time',
  'Tree': 'fa-solid:tree',
  'Tshirt': 'fa-solid:tshirt',
  'Wand': 'fa:magic',
  'Water': 'mdi:water',
  'Wind': 'fa-solid:wind',
} as { [key: string]: string };
