@baseUrl = http://localhost:3001
@id = {{getAllConfigs.response.body.$[0]._id}}

###
# @name getAllConfigs
GET {{baseUrl}}/config HTTP/1.1
content-type: application/json

###
# @name getConfig
GET {{baseUrl}}/config/{{id}} HTTP/1.1
content-type: application/json

###
# @name createConfig
POST {{baseUrl}}/config HTTP/1.1
content-type: application/json

{
  "name": "Example Config",
  "shortName": "Example",
  "description": "An example config for testing",
  "imageUrl": "http://localhost/invalid-url"
}

###
# @name updateConfig
PUT {{baseUrl}}/config HTTP/1.1
content-type: application/json

{
  "_id": "{{id}}",
  "name": "Updated Example Config",
  "shortName": "Updated Example",
  "description": "An example updated config for testing",
  "imageUrl": "http://localhost/updated-invalid-url"
}

###
# @name deleteConfig
DELETE {{baseUrl}}/config/{{id}} HTTP/1.1
content-type: application/json
